model:
  name: logist_regression_model
author: Ziying Wang
version: AA1
description: Predicts a student admission result given his background
tags:
  - classifier
dependencies: requirements.txt

load_data:
  how: download_from_s3


generate_features:
  reset_y:
    cutoff: 0.7
  get_features: 
    selected_columns: [GRE Score,TOEFL Score,University Rating, SOP, LOR, CGPA,Research]
    save_path: data/admission_to_train.csv
    target: Chance of Admit
  get_target:
    target: Chance of Admit
    save_target: data/admission_result.csv


train_model:
  method: logistic
  get_features:
    selected_columns: [GRE,TOEFL,University_rating, SOP, LOR , CGPA , Research]
  get_target:
    target: result
  train_test_split:
    train_ratio: 0.8
    test_ratio: 0.2
    random_seed: 42
    save_split: data/admission-data-
  save_model: models/logreg.pkl


score_model:
  model_path: models/logreg.pkl
  get_features:
    selected_columns: [GRE,TOEFL,University_rating, SOP,LOR,CGPA,Research]
  get_target:
    target: result
  train_test_split:
    train_ratio: 0.8
    test_ratio: 0.2
    random_seed: 42
  get_new_student:
    new_CGPA: 7.5
    new_GRE: 300
    new_LOR: 3
    new_Research: 1
    new_SOP: 3
    new_TOEFL: 100
    new_University_rating: 3
    save_new_student: data/new_student.csv
  save_score: models/new_student_prediction.csv

test_model:
  path_to_test_features: data/admission-data--train-features.csv
  model_path: models/logreg.pkl
  get_features:
    selected_columns: [GRE,TOEFL,University_rating, SOP,LOR,CGPA,Research]
  get_target:
    target: result
  train_test_split:
    train_ratio: 0.8
    test_ratio: 0.2
    random_seed: 42
  save_score: models/admission_prediction.csv

evaluate_model:
  model_path: models/logreg.pkl
  metrics: [auc, accuracy]
  save_eval: models/model_evaluation.csv
  path_to_test_features: data/admission-data--train-features.csv
  path_to_test_target: data/admission-data--test-targets.csv 
  get_features:
    selected_columns: [GRE,TOEFL,University_rating, SOP,LOR,CGPA,Research]


post_model:
  model_path: models/logreg.pkl
  get_features: 
    selected_columns: [GRE,TOEFL,University_rating, SOP,LOR,CGPA,Research]
  get_new_student:
    new_CGPA: 7.5
    new_GRE: 300
    new_LOR: 3
    new_Research: 1
    new_SOP: 3
    new_TOEFL: 100
    new_University_rating: 3
    save_new_student: data/new_student.csv


  
